apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: callcenterai-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:

  # Main Web App
  - host: callcenterai.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: callcenterai-app-service
            port:
              number: 5000

  # ArgoCD UI
  - host: argocd.callcenterai.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80

  # Kubernetes Dashboard
  - host: k8s.callcenterai.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80

  # Prometheus
  - host: prometheuse.callcenterai.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80

  # Grafana
  - host: grafana.callcenterai.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80