apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenterai-transformer-deployment
  labels:
    app: callcenterai-transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenterai-transformer
  template:
    metadata:
      labels:
        app: callcenterai-transformer
    spec:
      containers:
        - name: callcenterai-transformer
          image: medhedimaaroufi/callcenterai-transformer:v1.0.1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: callcenterai-transformer-config
            - secretRef:
                name: callcenterai-transformer-secret
          # Optional: set resource limits
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: callcenterai-transformer-service
spec:
  selector:
    app: callcenterai-transformer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
